name: Test Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    strategy:
      matrix:
        python: ['3.6', '3.10']
    steps:
      # Python & dependency installation
      - uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install Poetry
        uses: snok/install-poetry@v1.2.1
      - name: set poetry config path
        run: poetry config virtualenvs.path ~/.virtualenvs
      - name: install dependencies
        run: poetry install -E pandas
      - name: lint with flake8
        run: poetry run flake8 --show-source --statistics --ignore=E203,E501,W503 src
      - name: pytest
        run: poetry run pytest
        env:
          OPENSTATES_API_KEY: ${{ secrets.OPENSTATES_API_KEY }}
    runs-on: ubuntu-20.04
